version: '3.9'
services:
  discovery:
    image: discovery:latest
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - shop-network

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - shop-network

networks:
  shop-network:
    driver: bridge